' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/28/05 by LEGRE
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("C:\Documents and Settings\LEGRE\Bureau\olivier\kholle info assemblage\sinusmatic_t_SW\porte peage eleves.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("porte peage eleves")
swApp.ActiveDoc.ActiveView.FrameWidth = 1059
swApp.ActiveDoc.ActiveView.FrameHeight = 706
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3276850510439, 0.07273516220664, -0.2860981823815, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4543703593812, -0.04379858454422, -0.2272445681597, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.136073605011, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4311547146925, 0.05197646000101, -0.2577606666576, False, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0.0186629, 0
Part.ActiveView().RotateAboutCenter 0.102646, 0.0202373
Part.ActiveView().RotateAboutCenter 0.0839832, 0.0101186
Part.ActiveView().RotateAboutCenter 0.111978, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0746517, 0.0101186
Part.ActiveView().RotateAboutCenter 0.326601, 0.0708304
Part.ActiveView().RotateAboutCenter 0.0653202, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0933146, 0.0202373
Part.ActiveView().RotateAboutCenter 0.13064, 0.0404745
Part.ActiveView().RotateAboutCenter 0.102646, 0.0303559
Part.ActiveView().RotateAboutCenter 0.149303, 0.0303559
Part.ActiveView().RotateAboutCenter 0.177298, 0
Part.ActiveView().RotateAboutCenter 0.0746517, 0.0202373
Part.ActiveView().RotateAboutCenter 0.0186629, 0
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2428665028411, 0.09439884632661, -0.2947272353829, False, 0, Nothing)
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter -0.0933146, -0.0202373
Part.ActiveView().RotateAboutCenter -0.102646, -0.0202373
Part.ActiveView().RotateAboutCenter -0.121309, -0.0101186
Part.ActiveView().RotateAboutCenter -0.167966, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0404745
Part.ActiveView().RotateAboutCenter -0.0839832, 0.0404745
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0746517, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0279944, 0
Part.ActiveView().RotateAboutCenter -0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0186629, 0
Part.ActiveView().RotateAboutCenter 0.0466573, 0
Part.ActiveView().RotateAboutCenter 0.0653202, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0653202, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0373259, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0373259, 0
Part.ActiveView().RotateAboutCenter 0.0279944, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0279944, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0607118
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0746517, -0.0505931
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0186629, -0.0101186
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1004301104971, -0.005357501793583, -0.08694892028603, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.1424363923439, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
' MSGBOX
' L'assemblage ne peut pas être résolu en ajoutant cette contrainte.   Considérez :
'      o Enlever la contrainte.
'     o Déplacer l'esquisse plus près de la solution désirée en faisant glisser ou en changeant les valeurs de cote.
'      o Ajouter des contraintes supplémentaires pour définir l'esquisse plus précisément.
'      o Changer le système de contrainte.

boolstatus = Part.Extension.SelectByID("", "FACE", -0.1448570528306, 0.1690262975313, 0.08199999999994, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2066044077458, 0.01212869064719, 0.08199999999999, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4311547146924, 0.0639892127881, -0.2864786521461, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0653202, 0
Part.ActiveView().RotateAboutCenter 0.25195, -0.0202373
Part.ActiveView().RotateAboutCenter 0.177298, 0
Part.ActiveView().RotateAboutCenter 0.214624, 0
Part.ActiveView().RotateAboutCenter 0.13064, 0.0101186
Part.ActiveView().RotateAboutCenter 0.121309, 0.0202373
Part.ActiveView().RotateAboutCenter 0.0653202, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0559888, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4088665028411, 0.07190724933221, -0.2825479770802, True, 0, Nothing)
Part.DeSelectByID "", "FACE", -0.4311547146924, 0.0639892127881, -0.2864786521461
Part.DeSelectByID "", "FACE", -0.2066044077458, 0.01212869064719, 0.08199999999999
Part.DeSelectByID "", "FACE", -0.4088665028411, 0.07190724933221, -0.2825479770802
boolstatus = Part.Extension.SelectByID("", "FACE", -0.408866502841, 0.08375850617907, -0.2823218075547, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0607118
Part.ActiveView().RotateAboutCenter -0.111978, 0.0505931
Part.ActiveView().RotateAboutCenter -0.0839832, 0.0404745
Part.ActiveView().RotateAboutCenter -0.0559888, 0.0404745
Part.ActiveView().RotateAboutCenter -0.0559888, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0933146, 0
Part.ActiveView().RotateAboutCenter -0.0559888, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0466573, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0466573, 0
Part.ActiveView().RotateAboutCenter -0.0559888, 0
Part.ActiveView().RotateAboutCenter -0.102646, 0
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0839832, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0101186
Part.ActiveView().RotateAboutCenter -0.102646, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0101186
Part.ActiveView().RotateAboutCenter -0.00933146, 0
Part.ActiveView().RotateAboutCenter -0.00933146, 0
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4311547146924, 0.06427457667337, -0.285828747642, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.02228821185122, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.5021771096183, 0.1509722662462, -0.3536618292534, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0559888, 0
Part.ActiveView().RotateAboutCenter 0.158635, -0.0202373
Part.ActiveView().RotateAboutCenter 0.205292, -0.0607118
Part.ActiveView().RotateAboutCenter 0.13064, 0
Part.ActiveView().RotateAboutCenter 0.158635, -0.0505931
Part.ActiveView().RotateAboutCenter 0.13064, -0.0303559
Part.ActiveView().RotateAboutCenter 0.158635, -0.0505931
Part.ActiveView().RotateAboutCenter 0.121309, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0466573, -0.0202373
Part.ActiveView().RotateAboutCenter 0.0373259, 0
Part.ActiveView().RotateAboutCenter 0.0466573, 0
Part.ActiveView().RotateAboutCenter 0.0279944, 0
Part.ActiveView().RotateAboutCenter 0.0559888, -0.0202373
Part.ActiveView().RotateAboutCenter 0.0746517, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, 0
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
boolstatus = Part.Extension.SelectByID("", "FACE", -0.458866502841, 0.05910637926135, -0.2851113938526, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.04331060677702, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4720178609639, 0.1584790726369, -0.3106486287783, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4824523363432, 0.06594338593004, -0.2776012511104, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.09463951514807, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0839832, 0
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0303559
Part.ActiveView().RotateAboutCenter -0.111978, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0746517, 0
Part.ActiveView().RotateAboutCenter -0.102646, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0559888, 0
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0279944, 0.0202373
Part.ActiveView().RotateAboutCenter 0.0466573, 0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0186629, 0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0101186
boolstatus = Part.Extension.SelectByID("", "EDGE", -0.4453999001882, -0.007459321110446, -0.3068581916328, True, 0, Nothing)
Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("", "FACE", -0.4432300779393, -0.1094778849856, -0.3213516203988, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2149192216528, 0.07102951352107, -0.2928359918181, True, 0, Nothing)
Part.AddMate 6, 2, False, 0.2012743167415, 2.426007660272
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0505931
Part.ActiveView().RotateAboutCenter -0.111978, -0.151779
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0910676
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0708304
Part.ActiveView().RotateAboutCenter -0.0839832, -0.080949
Part.ActiveView().RotateAboutCenter -0.0746517, -0.0708304
Part.ActiveView().RotateAboutCenter -0.0746517, -0.0708304
Part.ActiveView().RotateAboutCenter -0.0186629, -0.0101186
Part.ActiveView().RotateAboutCenter 0, -0.0101186
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1394040123167, 0.2004139863002, -0.3359997942412, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1338145466769, 0.11042619856, -0.2667043609033, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.024156059957, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1280619132372, 0.1423477217553, -0.3069271165155, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1466067900605, 0.04196015929585, -0.2364039321592, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.1225820091261, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0373259, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0101186
Part.ActiveView().RotateAboutCenter -0.102646, 0
Part.ActiveView().RotateAboutCenter -0.111978, 0.0101186
Part.ActiveView().RotateAboutCenter -0.111978, 0.0505931
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0404745
Part.ActiveView().RotateAboutCenter -0.0559888, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0186629, 0.0101186
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0404745
Part.ActiveView().RotateAboutCenter 0, 0.080949
Part.ActiveView().RotateAboutCenter -0.0279944, 0.151779
Part.ActiveView().RotateAboutCenter -0.00933146, 0.080949
Part.ActiveView().RotateAboutCenter 0, 0.0202373
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0279944, 0.0303559
Part.ActiveView().RotateAboutCenter 0.111978, 0.192254
Part.ActiveView().RotateAboutCenter 0.00933146, 0.182135
Part.ActiveView().RotateAboutCenter -0.0933146, 0.151779
Part.ActiveView().RotateAboutCenter -0.195961, 0
Part.ActiveView().RotateAboutCenter -0.214624, -0.344033
Part.ActiveView().RotateAboutCenter -0.0279944, -0.273203
Part.ActiveView().RotateAboutCenter 0.139972, -0.29344
Part.ActiveView().RotateAboutCenter 0.139972, -0.0505931
Part.ActiveView().RotateAboutCenter 0.0933146, 0.080949
Part.ActiveView().RotateAboutCenter 0.0186629, 0.151779
Part.ActiveView().RotateAboutCenter -0.0373259, 0.22261
Part.ActiveView().RotateAboutCenter -0.261281, 0.141661
Part.ActiveView().RotateAboutCenter -0.121309, -0.192254
Part.ActiveView().RotateAboutCenter 0.158635, -0.22261
Part.ActiveView().RotateAboutCenter 0.13064, -0.0303559
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0404745
Part.ActiveView().RotateAboutCenter -0.149303, 0.080949
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0, -0.0303559
Part.ActiveView().RotateAboutCenter 0, -0.0708304
Part.ActiveView().RotateAboutCenter 0, -0.0607118
Part.ActiveView().RotateAboutCenter 0, -0.101186
Part.ActiveView().RotateAboutCenter 0, -0.0404745
Part.ActiveView().RotateAboutCenter 0, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0202373
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0466573, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0559888, -0.0404745
Part.ActiveView().RotateAboutCenter 0.0653202, -0.0404745
Part.ActiveView().RotateAboutCenter 0.0559888, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0373259, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0746517, -0.0404745
Part.ActiveView().RotateAboutCenter 0.0466573, -0.0202373
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3418761527684, 0.05307839109628, -0.2632563873599, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1154721865758, 0.03935797664343, -0.08488192038831, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.1731373329149, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
' MSGBOX
' L'assemblage ne peut pas être résolu en ajoutant cette contrainte.   Considérez :
'      o Enlever la contrainte.
'     o Déplacer l'esquisse plus près de la solution désirée en faisant glisser ou en changeant les valeurs de cote.
'      o Ajouter des contraintes supplémentaires pour définir l'esquisse plus précisément.
'      o Changer le système de contrainte.

Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2220592641974, 0.04641137895243, -0.2769947314488, False, 0, Nothing)
Part.SetPickMode
Part.ClearSelection
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2964572556962, 0.05308012383335, -0.2632833207514, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3119508637639, 0.06103845254302, -0.2800051079888, False, 0, Nothing)
' MSGBOX
' Le composant sélectionné est fixé. Il ne peut pas être déplacé.

Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3389494141189, 0.05518170066705, -0.2718167308628, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3162575885546, 0.06126103620477, -0.2802088127549, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2129248850225, 0.06079917591961, -0.286252981186, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("ArbreFourche-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.UnfixComponent
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-2@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.SetUserPreferenceToggle(197, False)
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bati-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.SetUserPreferenceToggle(197, True)
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bati-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/reducteur-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.SetUserPreferenceToggle(13, True)
boolstatus = Part.SetUserPreferenceToggle(13, False)
boolstatus = Part.Extension.SelectByID("Plateau-1@porte peage eleves", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0303559
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0505931
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0708304
Part.ActiveView().RotateAboutCenter 0, 0.0708304
Part.ActiveView().RotateAboutCenter 0, 0.0404745
Part.ActiveView().RotateAboutCenter 0, 0.0303559
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0, -0.0202373
Part.ActiveView().RotateAboutCenter 0.0186629, -0.101186
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0708304
Part.ActiveView().RotateAboutCenter 0, -0.0607118
Part.ActiveView().RotateAboutCenter 0, -0.0607118
Part.ActiveView().RotateAboutCenter -0.00933146, -0.0303559
Part.ActiveView().RotateAboutCenter -0.00933146, -0.0101186
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3113596763822, 0.05858181243622, -0.2773765438784, False, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3339541644535, 0.0548851364025, -0.271121180044, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.1170367583208, 0.03988783346017, -0.08568927494034, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.1731373329149, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3245490827019, -0.003348332982227, -0.1107356417327, False, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/reducteur-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3346018593942, -0.0055520879597, -0.1049645665905, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2959975589821, -0.03849003321398, -0.122854494058, False, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-2@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.3589185821964, -0.01065266358779, -0.0887270579982, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0373259, 0
Part.ActiveView().RotateAboutCenter 0.0933146, 0
Part.ActiveView().RotateAboutCenter 0.167966, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0839832, -0.0202373
Part.ActiveView().RotateAboutCenter 0.0933146, -0.0202373
Part.ActiveView().RotateAboutCenter 0.0559888, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0466573, 0
Part.ActiveView().RotateAboutCenter 0.0746517, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0373259, 0
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0101186
Part.ActiveView().RotateAboutCenter 0.102646, 0
Part.ActiveView().RotateAboutCenter 0.0746517, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0746517, -0.0303559
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0933146, -0.0404745
Part.ActiveView().RotateAboutCenter 0.13064, -0.0708304
Part.ActiveView().RotateAboutCenter 0.102646, -0.0505931
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
Part.ActiveView().RotateAboutCenter -0.00933146, 0
Part.ActiveView().RotateAboutCenter -0.0373259, 0
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0559888, 0
Part.ActiveView().RotateAboutCenter -0.0746517, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0746517, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0373259, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0466573, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0279944, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter -0.0373259, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0101186
Part.ActiveView().RotateAboutCenter -0.00933146, 0
Part.ActiveView().TranslateBy 0, -0.000395191
Part.ActiveView().TranslateBy -0.00118557, -0.00158076
Part.ActiveView().TranslateBy -0.00237115, -0.00592786
Part.ActiveView().TranslateBy -0.00316153, -0.00513748
Part.ActiveView().TranslateBy -0.00553267, -0.00711344
Part.ActiveView().TranslateBy -0.00474229, -0.00632306
Part.ActiveView().TranslateBy -0.00513748, -0.0086942
Part.ActiveView().TranslateBy -0.00750863, -0.0106702
Part.ActiveView().TranslateBy -0.00395191, -0.00474229
Part.ActiveView().TranslateBy -0.00395191, -0.00632306
Part.ActiveView().TranslateBy -0.00711344, -0.010275
Part.ActiveView().TranslateBy -0.00632306, -0.00829901
Part.ActiveView().TranslateBy -0.00355672, -0.00474229
Part.ActiveView().TranslateBy -0.000790382, -0.00118557
Part.ActiveView().TranslateBy -0.00158076, -0.0043471
Part.ActiveView().TranslateBy -0.00395191, -0.00908939
Part.ActiveView().TranslateBy -0.00355672, -0.00513748
Part.ActiveView().TranslateBy -0.00474229, -0.00790382
Part.ActiveView().TranslateBy -0.00474229, -0.00987977
Part.ActiveView().TranslateBy -0.00790382, -0.0118557
Part.ActiveView().TranslateBy -0.0193644, -0.0312201
Part.ActiveView().TranslateBy -0.00395191, -0.00987977
Part.ActiveView().TranslateBy -0.000790382, -0.00316153
Part.ActiveView().TranslateBy 0, -0.000395191
Part.ActiveView().TranslateBy 0.000395191, -0.000790382
Part.ActiveView().TranslateBy 0, -0.000395191
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2644301104972, -0.001824472168551, -0.07945137706849, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.09448847169913, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("", "FACE", -0.2594301104972, 0.01424140951741, 0.0731726946272, False, 0, Nothing)
Part.ActiveView().RotateAboutCenter -0.0186629, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0186629, 0.0101186
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0559888, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0101186
Part.ActiveView().RotateAboutCenter 0, 0
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0559888, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0933146, 0.0303559
Part.ActiveView().RotateAboutCenter -0.111978, 0.0202373
Part.ActiveView().RotateAboutCenter -0.111978, 0.0303559
Part.ActiveView().RotateAboutCenter -0.0653202, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0373259, 0
Part.ActiveView().RotateAboutCenter -0.0186629, 0
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0101186
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Ecrou-1@porte peage eleves", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.000904403481286, 0.2077408263071, -0.1489732438675, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", 0.02405663893501, 0.0151383836415, -0.1129793790676, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.139073993143, 3.105644209397
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bati-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/reducteur-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Vis-2@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", 0.004187194438373, 0.1598635218733, -0.2090484026082, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0202373
Part.ActiveView().RotateAboutCenter -0.0279944, 0.080949
Part.ActiveView().RotateAboutCenter -0.0746517, 0.151779
Part.ActiveView().RotateAboutCenter -0.0653202, 0.172017
Part.ActiveView().RotateAboutCenter -0.0373259, 0.101186
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0708304
Part.ActiveView().RotateAboutCenter -0.0279944, 0.080949
Part.ActiveView().RotateAboutCenter -0.0373259, 0.080949
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0607118
Part.ActiveView().RotateAboutCenter 0, 0.0303559
Part.ActiveView().RotateAboutCenter 0, 0.0202373
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0303559
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0404745
Part.ActiveView().RotateAboutCenter 0, 0.0505931
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0404745
Part.ActiveView().RotateAboutCenter -0.00933146, 0
Part.ActiveView().RotateAboutCenter 0, 0.0202373
boolstatus = Part.Extension.SelectByID("", "FACE", 0.03464530734732, 0.01105400778283, -0.07500408935056, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.1987045473883, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0404745
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0404745
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0303559
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0202373
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0303559
Part.ActiveView().RotateAboutCenter 0.00933146, -0.0404745
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0303559
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0505931
Part.ActiveView().RotateAboutCenter 0.0279944, -0.0708304
Part.ActiveView().RotateAboutCenter 0, -0.0404745
Part.ActiveView().RotateAboutCenter 0.0186629, -0.0404745
Part.ActiveView().RotateAboutCenter 0, -0.0202373
Part.ActiveView().RotateAboutCenter 0, -0.0202373
Part.ActiveView().RotateAboutCenter 0, -0.0202373
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter 0.0186629, 0
Part.ActiveView().RotateAboutCenter 0.0559888, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0466573, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0373259, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0279944, 0
Part.ActiveView().RotateAboutCenter 0.0466573, 0
Part.ActiveView().RotateAboutCenter 0.0279944, 0
Part.ActiveView().RotateAboutCenter 0.00933146, 0
Part.ActiveView().RotateAboutCenter 0.0466573, 0
Part.ActiveView().RotateAboutCenter 0.0279944, 0
Part.ActiveView().RotateAboutCenter 0.0279944, 0
Part.ActiveView().RotateAboutCenter 0.0279944, -0.0101186
boolstatus = Part.Extension.SelectByID("Croisillon-1@porte peage eleves", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Vis-3@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
Part.ActiveView().RotateAboutCenter 0, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0505931
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0607118
Part.ActiveView().RotateAboutCenter -0.0933146, -0.080949
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0505931
Part.ActiveView().RotateAboutCenter -0.0933146, -0.0607118
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0202373
Part.ActiveView().RotateAboutCenter -0.102646, -0.0505931
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0186629, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0559888, -0.0303559
Part.ActiveView().RotateAboutCenter -0.0933146, -0.0607118
Part.ActiveView().RotateAboutCenter -0.111978, -0.101186
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0708304
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0653202, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0186629, -0.0202373
Part.ActiveView().RotateAboutCenter -0.0279944, -0.0101186
Part.ActiveView().RotateAboutCenter -0.0746517, -0.0505931
Part.ActiveView().RotateAboutCenter -0.0466573, -0.0404745
Part.ActiveView().RotateAboutCenter -0.0839832, -0.0607118
Part.ActiveView().RotateAboutCenter -0.0186629, -0.0101186
boolstatus = Part.Extension.SelectByID("", "FACE", 0.2503512242068, 0.1611674075871, 0.2773420572549, True, 0, Nothing)
Part.ActiveView().RotateAboutCenter 0, 0.0101186
Part.ActiveView().RotateAboutCenter 0.0466573, 0.0708304
Part.ActiveView().RotateAboutCenter 0.0653202, 0.121424
Part.ActiveView().RotateAboutCenter 0.0653202, 0.182135
Part.ActiveView().RotateAboutCenter 0.0466573, 0.172017
Part.ActiveView().RotateAboutCenter 0.0373259, 0.202373
Part.ActiveView().RotateAboutCenter 0, 0.202373
Part.ActiveView().RotateAboutCenter 0, 0.192254
Part.ActiveView().RotateAboutCenter 0.00933146, 0.202373
Part.ActiveView().RotateAboutCenter 0.00933146, 0.141661
Part.ActiveView().RotateAboutCenter 0, 0.121424
Part.ActiveView().RotateAboutCenter 0.00933146, 0.0708304
Part.ActiveView().RotateAboutCenter -0.00933146, 0.0404745
Part.ActiveView().RotateAboutCenter -0.00933146, 0.080949
Part.ActiveView().RotateAboutCenter 0, 0.0607118
boolstatus = Part.Extension.SelectByID("", "FACE", 0.04399243691881, 0.04564877100179, 0.09799999999996, True, 0, Nothing)
Part.AddMate 0, 2, False, 0.179342057255, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bati-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", 0.2306999507778, 0.1891206363813, 0.01553504435759, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", 0.02890180242991, 0.03155211583268, 0.04683716865787, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.2925822945453, 0
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-1@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "FACE", 0.03040990222331, 0.09349415524798, -0.003673833654773, False, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves/Bague-2@Bati", "COMPONENT", 0, 0, 0, True, 0, Nothing)
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("", "FACE", -0.03037763999845, 0.09188540140016, -0.01919772737563, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("", "FACE", 0.01195185988001, 0.08668770879584, 0.03275517151735, True, 0, Nothing)
Part.AddMate 1, 2, False, 0.03074577936356, 0.4366889529508
Part.ClearSelection
Part.WindowRedraw
Part.WindowRedraw
Part.WindowRedraw
Part.TranslateComponent
boolstatus = Part.Extension.SelectByID("", "EDGE", 0.01923121083308, 0.1284740945563, 0.003783819533965, False, 0, Nothing)
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "porte peage eleves"
