' ******************************************************************************
' swxJRNL.swj - journal recorded on 02/28/05 by CLIENT
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("F:\kholle info assemblage\sinusmatic_t_SW\porte peage eleves.SLDASM", 2, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("porte peage eleves")
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ActiveDoc.ActiveView.FrameState = 1
boolstatus = Part.Extension.SelectByID("ArbreFourche-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.UnfixComponent
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("Ecrou-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Barre-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Goupille-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("ArbreFourche-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Porte-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Rotule-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Croisillon-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Plateau-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Bati-1@porte peage eleves", "COMPONENT", 0, 0, 0, False, 0, Nothing)
Part.ClearSelection
Part.Save2 FALSE
swApp.ActiveDoc.ActiveView.FrameState = 1
swApp.ExitApp
End Sub
